base: &base
  adapter: postgresql
  host: localhost
  port: 5432
  database: benchlingchallenge_development
  username: josh
  password: password
  schema_search_path: public

development:
  <<: *base

production:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev

staging:
  <<: *base

test:
  <<: *base
